eureka:
  instance:
    hostname: ${APP_HOST:localhost}
    client:
      serverUrl:
        defaultZone: http://${APP_DISCOVERY_SERVER_HOST:localhost}:${APP_DISCOVERY_SERVER_PORT:8761}/eureka/
