server:
  address: localhost
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME:employee_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASS:pass}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
