spring:
  datasource:
    url: jdbc:oracle:thin:@${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${DB_NAME:testdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
  #liquibase:
    #contexts: oracle