spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME:testdb};DB_CLOSE_ON_EXIT=FALSE
    username: ${DB_USERNAME:sa}
    password: ${DB_PASS:pass}
    driverClassName: org.h2.Driver
  jpa:
    #defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  #liquibase:
    #contexts: h2