server:
  address: ${APP_HOST:localhost}
  # https://www.geeksforgeeks.org/spring-boot-random-dynamic-port-allocation/
  port: ${APP_PORT:0} # Random/Dynamic Port:

spring:
  jpa:
    hibernate:
      ddl-auto: none

app:
  startup:
    message: "app is started up succesfully"
