# https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html
server:
  address: ${APP_HOST:localhost}
  # We can let Spring Boot choose a random port for us because later we’ll access this service with its name.
  port: ${APP_PORT:0}

eureka:
  instance:
    hostname: ${APP_HOST:localhost}
#    prefer-ip-address: true
    prefer-ip-address: false
    client:
      register-with-eureka: true
      # If we configure this property as true,
      # the inbuilt client will try to fetch the Eureka registry.
      fetch-registry: true
      serverUrl:
        defaultZone: ${HTTP_PROTOCOL:http}://${APP_DISCOVERY_SERVER_HOST:localhost}:${APP_DISCOVERY_SERVER_PORT:8761}/eureka/
