server:
  address: ${APP_HOST:localhost}
  # https://www.geeksforgeeks.org/spring-boot-random-dynamic-port-allocation/
  port: ${APP_PORT:0} #
  compression:
    enabled: ${SERVER_COMPRESSION:true}
  error:
    whitelabel:
      enabled: true
  http2:
    enabled: ${ENABLE_HTTP2:false}

eureka:
  instance:
    hostname: ${APP_HOST:localhost}
#    prefer-ip-address: true
    prefer-ip-address: false
    client:
      serverUrl:
        defaultZone: ${HTTP_PROTOCOL:http}://${APP_DISCOVERY_SERVER_HOST:localhost}:${APP_DISCOVERY_SERVER_PORT:8761}/eureka/

spring:
  application:
    admin:
      enabled: true
  # disable zipkin tracing
  # https://stackoverflow.com/questions/75474597/how-to-disable-zipkin-reporter-in-spring-boot-3
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration      
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
#  jackson:
#    default-property-inclusion: non_null
#    serialization:
#      write_dates_as_timestamps: false
#    deserialization:
#      accept_empty_string_as_null_object: true
#  liquibase:
#    change-log: classpath:/db/changelog/changelog-master.xml

# https://springdoc.org/
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
    groups:
      enabled: true
  #packages-to-scan: '*'
  #paths-to-match: '*'
  paths-to-exclude:
    - "/fve/**"
  cache:
    disabled: true
  show-actuator: false
  writer-with-default-pretty-printer: true
  use-management-port: false
  enable-spring-security: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tryItOutEnabled: true
    csrf:
      enabled: false

app:
  startup:
    message: "app is started up succesfully"
  info:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  swagger:
    api-info:
      title: "REST API MS TITLE"
      description: ${app.description}
      license-name: "Internal use only"
      contact:
        name: "FVE team"
        email: "team@fve.be"
    controller-package: org.fve.sampleprojects.controller
  microservice:
    jasypt:
      encryptor:
        password:
          index: 2

logging:
  charset:
    console: "UTF-8"
    file: "UTF-8"
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org:
      hibernate:
        type: ${LOGGING_LEVEL_HIBERNATE:INFO}
      springframework:
        web: ${LOGGING_LEVEL_SPRING:INFO}
  file:
    name: ${LOG_FILE_NAME:./var/logs/${spring.application.name}.log}
#  pattern:
#    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  logback:
    rollingpolicy:
      #      file-name-pattern: ./var/logs/app.%d{yyyy-MM-dd}.%i.log
      file-name-pattern: ${LOG_FILE_NAME_PATTERN:./var/logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log}

  
management:
  endpoint:
    auditevents:
      enabled: true
    beans:
      enabled: true
    caches:
      enabled: true
    conditions:
      enabled: true
    configprops:
      enabled: true
      show-values: always
    env:
      enabled: true
      show-values: always
    info:
      enabled: true
    liquibase:
      enabled: true
    logfile:
      enabled: true
      external-file: ${logging.file.name}
    scheduledtasks:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
        #include: refresh, info, health, prometheus
      discovery:
        enabled: true
    enabled-by-default: true
    jmx:
      domain: org.fve.services.${spring.application.name}
#      domain: org.fve.sampleprojects.msservice     
  info:
    build.enabled: true
    defaults.enabled: true
    git:
      enabled: true
      mode: full
    env.enabled: true
    java.enabled: true        
    os.enabled: true
  health:
    diskspace.enabled: false
    db.enabled: true
    jms.enabled: true
    livenessstate.enabled: false
    mail.enabled: true
    ping.enabled: true
    rabbit.enabled: true
    readinesstate.enabled: false
    redis.enabled: false

#using the metadata
#spring.boot.admin.client.instance.metadata.tags.environment=test

# spring boot extra information tags
# using the info endpoint
info:
  tags:
    environment: local
    profiles: ${spring.profiles.active}

# for jasypt-encryptor-boot-starter
#jasypt:
  #encryptor:
    #algorithm: PBEWithMD5AndDES
    #iv-generator-classname: org.jasypt.iv.NoIvGenerator